install:
	pip install --upgrade pip &&\
	pip install -r requirements.txt

format:
	black *.py

train:
	python src/pipeline/train.py

eval:
	echo "## Model Metrics" > report.md
	cat ./results/metrics.txt >> report.md

	echo '## Predicted vs Actual Scatter Plot' >> report.md
	echo '![Scatter Plot](./results/scatter_plot.png)' >> report.md

	cml comment create report.md

	

