name: ML Pipeline CI

# Trigger the workflow on any push to the main branch or pull request
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    # Optionally, you can also trigger the workflow manually
    workflow_dispatch:


# Permissions for the workflow      
permissions: write-all
jobs:

    test:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Check out the code from the repository
            - name: Check out code
              uses: actions/checkout@v2
            
            # Step 2: Set up Python environment
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.11'
            
            # Step 3: Install dependencies
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            # Steps 4: Run tests
            - name: Run tests
              run: pytest
    
    build:
        needs: test
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v3
          - uses: iterative/setup-cml@v2
          - name: Install Packages
            run: make install
          - name: Format
            run: make format
          - name: Train
            run: make train
          - name: Evaluation
            env:
              REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}  
            run: make eval



            

