name: ML CT Pipeline

# Trigger the workflow on any push to the main branch or pull request
on:
  # Trigger when the previous workflow (ML CI Pipeline) has completed
#  workflow_run:
#    workflows: ["ML CI Pipeline"]
#    types:
#      - completed
    pull_request:
        branches:
            - main

    # Trigger daily at 12 AM
    schedule:
      - cron: '0 0 * * *'

    # Optionally, you can also trigger the workflow manually
    workflow_dispatch:


# Permissions for the workflow      
permissions: write-all
jobs:

    build:
        runs-on: ubuntu-latest

        steps:
          # Step 1: Check out the code from the repository
          - name: Check out code
            uses: actions/checkout@v3

          # Step 2: Set up CML
          - name: Set up CML
            uses: iterative/setup-cml@v2

          # Step 3: Set up Python environment
          - name: Install Packages
            run: make install_cml

          # Step 4: Format code
          - name: Format
            if: ${{ success() }}
            run: make format
          
          # Step 5: Run training
          - name: Train
            if: ${{ success() }}
            run: make train

          # Step 6: Run Evaluation
          - name: Evaluation
            if: ${{ success() }}
            env:
              REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}  
            run: make eval

          # Step 7: Upload the branch
          - name: Update Branch
            env:
              NAME: ${{ secrets.USER_NAME }}
              EMAIL: ${{ secrets.USER_EMAIL }}
            run: make update-branch USER_NAME=$NAME USER_EMAIL=$EMAIL



            

